version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      PORT: 3000
      TEST_PORT: 3001
    ports:
      - "3000:3000"
    depends_on:
      pgdb:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:3000/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgdb:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRESQL_DATABASE=${DB_NAME}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdb_data:/bitnami/postgresql

volumes:
  pgdb_data:
    driver: local
